language: php

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-ansi --no-interaction --no-suggest

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
